import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>
          {`
            .navbar {
              background-color: #111; /* Black background */
              color: #fff; /* White text */
            }
            .navbar .btn-ghost {
              color: #ffff; /* Red color for buttons */
              border: 1px solid gray;
            }
            .navbar .btn-ghost:hover {
              background-color: #f44336; /* Red background on hover */
              color: #fff; /* White text on hover */
            }
            .footer {
              background-color: #222; /* Dark grey footer */
              color: #white; /* Red text */
            }
            .footer p {
              font-size: 14px;
            }
            .footer .footer-center {
              color: #fff; /* White text in the center */
            }
            .navbar-center a {
              font-size: 1.5rem;
              color: #f44336; /* Red title */
            }
            .navbar-start a {
              color: #fff;
            }
            .navbar-logo {
              width: 40px;
              height: 40px;
              margin-right: 10px; /* Give some space between logo and text */
            }
          `}
        </style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar">
          <div className="navbar-start">
            <div className="dropdown">
              <div tabIndex={0} role="button" className="btn btn-ghost btn-circle">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-5 w-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M4 6h16M4 12h16M4 18h7" />
                </svg>
              </div>
              <ul
                tabIndex={0}
                className="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
                <li><a href="/">Homepage</a></li>
                <li><a href="/form">Formulir</a></li>
                <li><a href="/history">History</a></li>
              </ul>
            </div>
          </div>
          <div className="navbar-center">
            <div className="flex items-center">
              <img src="/images/LogoFastlane.png" alt="Logo" className="navbar-logo" />
              <a className="text-xl">Fastlane Garage</a>
            </div>
          </div>
          <div className="navbar-end">
            <button className="btn btn-ghost btn-circle">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </button>
            <button className="btn btn-ghost btn-circle">
              <div className="indicator">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-5 w-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                </svg>
                <span className="badge badge-xs badge-primary indicator-item"></span>
              </div>
            </button>
          </div>
        </div>
        {children}
        <footer className="footer footer-center bg-base-300 text-base-content p-4">
          <aside>
            <p>Copyright © {new Date().getFullYear()} - All rights reserved by Allarief</p>
          </aside>
        </footer>
      </body>
    </html>
  );
}
